name: frontend CI

on:
  push:
    branches: [ "frontend" ]
  pull_request:
    branches: [ "frontend" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: List root directory
      run: ls -al

    - name: List frontend directory
      run: ls -al frontend

    - name: â¬‡ï¸ì˜ì¡´ì„± ì„¤ì¹˜
      working-directory: ./frontend
      run: npm install

    - name: âœ… ìœ ë‹› í…ŒìŠ¤íŠ¸
      working-directory: ./frontend
      run: npm test

    - name: ğŸ“¦ í”„ë¡œì íŠ¸ ë¹Œë“œ
      working-directory: ./frontend
      run: npm run build

    # AWS S3
    - name: â¬†ï¸ S3 ì—…ë¡œë“œ
      uses: awact/s3-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: './frontend/build'  # ë¹Œë“œëœ ì •ì  íŒŒì¼ì´ ìœ„ì¹˜í•˜ëŠ” ë””ë ‰í† ë¦¬
        AWS_REGION: 'ap-northeast-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
